config/routes.rb
OnMangeOu::Application.routes.draw do
  resources :restos

  resources :lunches do
    resources :attendees
  end

  root 'lunches#index'

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  belongs_to :lunch
  has_many :choices
  has_many :restos, :through => :choices
  accepts_nested_attributes_for :choices
end

app/models/choice.rb
class Choice < ActiveRecord::Base

  belongs_to :resto
  belongs_to :attendee

end

app/models/lunch.rb
class Lunch < ActiveRecord::Base
  has_many :attendees, dependent: :destroy
  has_many :choices, :through => :attendees
end

app/models/resto.rb
class Resto < ActiveRecord::Base
  has_many :choices, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_lunch

  def create
    @attendee = @lunch.attendees.build(attendee_params)
    ch = choices_params
    ch.each do |c|
      @attendee.choices.build(:resto_id => c)
    end
    respond_to do |format|
      if @lunch.save
        format.html { redirect_to @lunch, notice: 'Lunch was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lunch }
      else
        format.html { render action: 'new' }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lunch
      @lunch = Lunch.find(params[:lunch_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendee_params
      params.require(:attendee).permit(:name)
    end

    def choices_params
      if (params[:attendee][:choice])
        return params[:attendee][:choice][:resto_id]
      else
        return []
      end
    end

end

app/controllers/lunches_controller.rb
class LunchesController < ApplicationController
  before_action :set_lunch, only: [:show, :edit, :update, :destroy]

  # GET /lunches
  # GET /lunches.json
  def index
    @lunches = Lunch.all
  end

  # GET /lunches/1
  # GET /lunches/1.json
  def show
    @attendee = @lunch.attendees.build
  end

  # GET /lunches/new
  def new
    @lunch = Lunch.new
  end

  # GET /lunches/1/edit
  def edit
  end

  # POST /lunches
  # POST /lunches.json
  def create
    @lunch = Lunch.new(lunch_params)

    respond_to do |format|
      if @lunch.save
        format.html { redirect_to @lunch, notice: 'Lunch was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lunch }
      else
        format.html { render action: 'new' }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lunches/1
  # PATCH/PUT /lunches/1.json
  def update
    respond_to do |format|
      if @lunch.update(lunch_params)
        format.html { redirect_to @lunch, notice: 'Lunch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lunches/1
  # DELETE /lunches/1.json
  def destroy
    @lunch.destroy
    respond_to do |format|
      format.html { redirect_to lunches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lunch
      @lunch = Lunch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lunch_params
      params.require(:lunch).permit(:date)
    end
end

app/controllers/restos_controller.rb
class RestosController < ApplicationController
  before_action :set_resto, only: [:show, :edit, :update, :destroy]

  # GET /restos
  # GET /restos.json
  def index
    @restos = Resto.all
  end

  # GET /restos/1
  # GET /restos/1.json
  def show
  end

  # GET /restos/new
  def new
    @resto = Resto.new
  end

  # GET /restos/1/edit
  def edit
  end

  # POST /restos
  # POST /restos.json
  def create
    @resto = Resto.new(resto_params)

    respond_to do |format|
      if @resto.save
        format.html { redirect_to @resto, notice: 'Resto was successfully created.' }
        format.json { render action: 'show', status: :created, location: @resto }
      else
        format.html { render action: 'new' }
        format.json { render json: @resto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restos/1
  # PATCH/PUT /restos/1.json
  def update
    respond_to do |format|
      if @resto.update(resto_params)
        format.html { redirect_to @resto, notice: 'Resto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @resto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restos/1
  # DELETE /restos/1.json
  def destroy
    @resto.destroy
    respond_to do |format|
      format.html { redirect_to restos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resto
      @resto = Resto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resto_params
      params.require(:resto).permit(:name,:phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/lunches_helper.rb
module LunchesHelper
end

app/helpers/restos_helper.rb
module RestosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnMangeOu</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="menu">
  <%= link_to 'Restaurants', restos_path %>
  <%= link_to 'On mange ou?', lunches_path %>
</div>
<div id="notice">
<% if flash[:alert] %>
    <p class="flash-error"><%= flash[:alert] %></p>
  <% end %>
  <% if flash[:notice] %>
    <p class="flash-notice"><%= flash[:notice] %></p>
  <% end %>
</div>
<div id="global">
  <%= yield %>
</div>
</body>
</html>

app/views/lunches/_form.html.erb
<%= form_for(@lunch) do |f| %>
  <% if @lunch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lunch.errors.count, "error") %> prohibited this lunch from being saved:</h2>

      <ul>
      <% @lunch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lunches/edit.html.erb
<h1>Editing lunch</h1>

<%= render 'form' %>

<%= link_to 'Show', @lunch %> |
<%= link_to 'Back', lunches_path %>

app/views/lunches/index.html.erb
<h1>OucétiKonAmangé?</h1>

<h2><%= link_to 'Nouveau sondage', new_lunch_path %></h2>

<% @lunches.each do |lunch| %>
  <%= link_to lunch.date, lunch %><br/>
<% end %>

app/views/lunches/new.html.erb
<h1>New lunch</h1>

<%= render 'form' %>

<%= link_to 'Back', lunches_path %>

app/views/lunches/show.html.erb
<h1>CéOuKonMange : <%= @lunch.date %></h1>

<%= form_for ([@lunch,@attendee]) do |f| %>
  <table id="choice_t">
    <tr>
      <th></th>
        <% Resto.all.each do |r| %>
          <th><%= link_to r.name, r %></th>
        <% end %>
    </tr>
    <% @lunch.attendees.each do |a| %>
      <tr>
        <td><%= a.name %></td>
        <% Resto.all.each do |r| %>
          <% if a.choices.select { |x| x.resto_id==r.id}.count > 0 %>
            <td>x</td>
          <% else %>
            <td></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
      <tr>
        <td><%= f.text_field :name %></td>
        <% Resto.all.each do |r| %>
          <td>
            <%= f.fields_for @attendee.choices.build do |ff| %>
              <%= ff.check_box(:resto_id, {:multiple => true},  r.id, nil) %>
            <% end %>
          </td>
        <% end %>
      </tr>
      <tr>
        <td>Total</td>
        <% Resto.all.each do |r| %>
          <td>
            <%= @lunch.choices.select { |x| x.resto_id == r.id  }.count %>
          </td>
        <% end %>
      </tr>

  </table>

  <%= f.submit "Submit" %>
<% end %>

app/views/restos/_form.html.erb
<%= form_for(@resto) do |f| %>
  <% if @resto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resto.errors.count, "error") %> prohibited this resto from being saved:</h2>

      <ul>
      <% @resto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
   <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restos/edit.html.erb
<h1>Editing resto</h1>

<%= render 'form' %>

<%= link_to 'Show', @resto %> |
<%= link_to 'Back', restos_path %>

app/views/restos/index.html.erb
<h1>OuKonPeuManger?</h1>
<h2><%= link_to 'Créer Un Autre Resto', new_resto_path %></h2>
<% @restos.each do |resto| %>
  <%= link_to resto.name, resto %>
  <%= ' (Tel : '+resto.phone.to_s+' ) ' %>
  <%= link_to 'x', resto, method: :delete, data: { confirm: 'Are you sure?' } %>
  <br/>
<% end %>

app/views/restos/new.html.erb
<h1>New resto</h1>

<%= render 'form' %>

<%= link_to 'Back', restos_path %>

app/views/restos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resto.name %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @resto.phone %>
</p>


<%= link_to 'Edit', edit_resto_path(@resto) %> |
<%= link_to 'Back', restos_path %>